### ISSUE TITLE
bug with pop up dialog

### ISSUE THREAD

**Issue by RDVSTUIKER** [deathbeam/example-plugin#52]
Is your feature request related to a problem? Please describe.
In the current form of the plugin it's very forceful with how it hides chat, so basically it never pops up other than with manual click. So it keeps hiding the usual stuff like level ups or NPC talking to you.

Describe the solution you'd like
It should just borrow the features from the filled mode when it's chat is hidden in similar way.

Describe alternatives you've considered
Only alternative is currently to just turn it off if I want to see the pop ups. But I prefer using fixed mode when I have multiple clients running since my filled mode for full screen play has very different settings and I use filled mode for it.

**Comment by Teut0nic** [comment]
Hello, I'm experiencing this bug too.  Before the latest osrs update, with the plugin turned on, resize viewport off, and the chatbox minmized, when a prompted chatbox appeared (talking to an npc, cooking a fish, etc., the chatbox would maximize and show the interactive chatbox window.  

Currently, with the same settings as above, the chatbox does not maximize and stays hidden.  For example, when I talk to an npc, the chatbox window does not maximize to display what the npc is saying.  I have to click on the "All" tab on the bottom left to show the interactive chatbox window.

Thank you for this plugin, I'm really enjoying it.

**Comment by t0000000fu** [comment]
Not sure if it helps to express I am also experiencing this bug. I thought I had imagined that the chat would maximize during npc options, but glad to see other people are experiencing this too.

**Comment by PoeticMania** [comment]
Started about yesterday as well, basically dialog window stays hidden no matter what, been really making it difficult to do a lot of things like talk to NPCs or use any teleport that asks you if you want to teleport.

**Comment by johnbakker123** [comment]
I have the same issue since the new update. The chatbox doesn't appear anymore whenever you do an action that the chatbox is needed for. This was in the past and would love to see it back.

**Comment by qapors** [comment]
Same issue, been playing with this plugin for ages.  when teleporting etc/talking to npcs chat has allways popped up. I cant play on normal fixed with chat cus im so used to this. really hoping it gets fixed :)

**Comment by v-e-n-g-i-e** [comment]
Also expericing this issue; absolutely love using this plugin and assume something was altered during the introduction of the mini-menu update. 

Hope to see this resolved soon, appreciate the plugin support!

**Comment by ghost** [comment]
> Also expericing this issue; absolutely love using this plugin and assume something was altered during the introduction of the mini-menu update.
> 
> Hope to see this resolved soon, appreciate the plugin support!

This was not a problem until the large Bounty Hunter update on 1/29/25.

**Comment by deathbeam** [comment]
I assume widget ids changed, if someone can check the new ones and then update would be nice. I can do it myself when i will be bored i guess, but the active PR to fix this issue isnt the correct solution I dont think.

**Comment by ghost** [comment]
> I assume widget ids changed, if someone can check the new ones and then update would be nice. I can do it myself when i will be bored i guess, but the active PR to fix this issue isnt the correct solution I dont think.

What do you mean the active PR? I'm guessing you mean public relations? IE in your eyes it is not an important issue since there are very few people posting issues, or am I wrong? For the past week I myself had been trying to figure out what the problem was. Only recently realized it was RuneLite. Then attempted to post an issue on their GitHub only to find out this was where I was supposed to be.
Since I had already seen multiple issues addressing the same one I am having, I didn't open a ticket.

My guess is there are a *lot* more people who this issue is affecting, but they aren't very technical and thus don't know how to make it here. Much less what the problem is or who to contact.

**Comment by deathbeam** [comment]
PR = pull request, so this: https://github.com/deathbeam/example-plugin/pull/53

E.g someone attemped to fix the issue but its not correct fix

**Comment by ghost** [comment]
> PR = pull request, so this: [#53](https://github.com/deathbeam/example-plugin/pull/53)
> 
> E.g someone attemped to fix the issue but its not correct fix

Well, that's a bit embarrassing. I've never been on GitHub before until this plugin stopped working so I'm not familiar with the acronyms and terminology. My apologies!

**Comment by Yookiop** [comment]
> I assume widget ids changed, if someone can check the new ones and then update would be nice. I can do it myself when i will be bored i guess, but the active PR to fix this issue isnt the correct solution I dont think.

I'm trying😭

![Image](https://github.com/user-attachments/assets/ee4973c9-789c-4a2e-8800-d9f920a56795)

**Comment by Yookiop** [comment]
@deathbeam I've searched for a while but this is the only thing I can find and I can't find a way to debug it since I dont have experience with Java or runelite development. I looked at runelite commit history around the time of last release and I see a commit of [Update Widget IDs to 2025-1-28](https://github.com/runelite/runelite/commit/26e332bffd9559949d2e564a75ed727230d5c9b4). Here the ID of chatbox-container is changed from 37 to 38, but I do not see a reference to ID number 37 in your code. I do see with the widget inspector that the chatbox-container is now hidden instead of visible, but idk if it was already hidden before last update and if that is relevant. If you're insterested in debugging together via Discord, I'm down to learn more about it and you can add me sensea9471, even setting up the Runelite development kit was awful with outdated youtube guides  

![Image](https://github.com/user-attachments/assets/d169436a-9641-4728-a179-2e93faf82c72)

**Comment by Yookiop** [comment]
@deathbeam  ok so I've finally figured out how to check the ID's ingame with that extremely tiny button that is added in developer mode. I can confirm that the ID's are still the same, so that shouldn't be the issue. However I'm very new to this, so I also could be wrong, I have checked options like DIALOG_NPC, DIALOG_SPRITE etc

![Image](https://github.com/user-attachments/assets/b58b2b73-9deb-409a-91bf-b8aa9e33c5b5)

**Comment by Shayzz1** [comment]
I appreciate the acknowledgement on this problem! thanks for trying to get it fixed

**Comment by deathbeam** [comment]
https://github.com/deathbeam/example-plugin/pull/56 fixed in

**Comment by chile8675** [comment]
> [#56](https://github.com/deathbeam/example-plugin/pull/56) fixed in

Is there anywhere I can donate to you?

You have no idea how thankful I am for this to have been fixed l0l

**Comment by ghost** [comment]
> [#56](https://github.com/deathbeam/example-plugin/pull/56) fixed in

I was actually just doing a quest and while most of the dialogue popped up, some didn't.
Not sure this is fixed entirely yet..

**Comment by ghost** [comment]
> [#56](https://github.com/deathbeam/example-plugin/pull/56) fixed in

He, so quick update.

I've played for a good few hours today and there are still many dialogues that are not fixed.
Some are in quests, some are when skipping a target in BH, repairing a firecape, etc.
Kinda hard to give you a full list but the issue is still ongoing.

**Comment by Rhinest1** [comment]
> > [#56](https://github.com/deathbeam/example-plugin/pull/56) fixed in
> 
> He, so quick update.
> 
> I've played for a good few hours today and there are still many dialogues that are not fixed. Some are in quests, some are when skipping a target in BH, repairing a firecape, etc. Kinda hard to give you a full list but the issue is still ongoing.

>Thought I'd just add that I played for a little while with it, npc dialogue works perfectly, crafting prompt pops up, npc contact spell works fine. However, I tried leaving the gauntlet and the dialogue didnt pop up to leave and I also tried some guardians of the rift where the chat box pop up for exceeding inventory space doesnt pop up.

**Comment by Rhinest1** [comment]
Hey! thought I'd just add that I played for a little while with it after the fix, npc dialogue worked perfectly fine for me, crafting prompt pops up, npc contact spell works fine. However, I tried leaving the gauntlet and the dialogue didnt pop up to leave and I also tried some guardians of the rift where the chat box pop up for exceeding inventory space doesnt pop up. No biggie thought I'd just let you know, hope this helps <3

**Comment by supyosup** [comment]
> > [#56](https://github.com/deathbeam/example-plugin/pull/56) fixed in
> 
> He, so quick update.
> 
> I've played for a good few hours today and there are still many dialogues that are not fixed. Some are in quests, some are when skipping a target in BH, repairing a firecape, etc. Kinda hard to give you a full list but the issue is still ongoing.



> Hey! thought I'd just add that I played for a little while with it after the fix, npc dialogue worked perfectly fine for me, crafting prompt pops up, npc contact spell works fine. However, I tried leaving the gauntlet and the dialogue didnt pop up to leave and I also tried some guardians of the rift where the chat box pop up for exceeding inventory space doesnt pop up. No biggie thought I'd just let you know, hope this helps <3

Do you guys have a test environment setup at all?

I am working on re-writing some of the code logic to catch more of these missed cases more easily but it's hard for me to test every single scenario such as BH stuff. I can try to help walk you guys through if you're interested in helping me test, let me know here or via discord, my username is oont

**Comment by ghost** [comment]
> > > [#56](https://github.com/deathbeam/example-plugin/pull/56) fixed in
> > 
> > 
> > He, so quick update.
> > I've played for a good few hours today and there are still many dialogues that are not fixed. Some are in quests, some are when skipping a target in BH, repairing a firecape, etc. Kinda hard to give you a full list but the issue is still ongoing.
> 
> > Hey! thought I'd just add that I played for a little while with it after the fix, npc dialogue worked perfectly fine for me, crafting prompt pops up, npc contact spell works fine. However, I tried leaving the gauntlet and the dialogue didnt pop up to leave and I also tried some guardians of the rift where the chat box pop up for exceeding inventory space doesnt pop up. No biggie thought I'd just let you know, hope this helps <3
> 
> Do you guys have a test environment setup at all?
> 
> I am working on re-writing some of the code logic to catch more of these missed cases more easily but it's hard for me to test every single scenario such as BH stuff. I can try to help walk you guys through if you're interested in helping me test, let me know here or via discord, my username is oont

he hey!
fuck it let it burn

**Comment by supyosup** [comment]
Most of this should be fixed in #60 

If you are having specific issues please open another request with more detailed notes and I can take a look.
